# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    static_configs:
      - targets: [ '0.0.0.0:9090' ]

  - job_name: 'netdata-client'

    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus-client ]

    honor_labels: true

    static_configs:
      - targets: [ '234:223', '1112:334', '43233:2455' ]

  - job_name: 'netdata-server'

    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus-server ]
    honor_labels: true

    static_configs:
      - targets: [ '235:555' ]